### ISSUE TITLE
Can't run XSTAMPP from Eclipse

### ISSUE THREAD

**Issue by ljy5490** [SE-Stuttgart/XSTAMPP#6]
Hi,

I followed the steps on the github but some errors came up when I tried to run xstampp.product. The following is the error message. Any idea about it? Thank you!

!SESSION 2018-10-31 11:03:02.738 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_181
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_AT
Framework arguments:  -product xstampp.xstampp_product
Command-line arguments:  -product xstampp.xstampp_product -data C:\Users\lij\Downloads\Software\Eclipse RCP RAP\eclipse-workspace/../runtime-xstampp.product -dev file:C:/Users/lij/Downloads/Software/Eclipse RCP RAP/eclipse-workspace/.metadata/.plugins/org.eclipse.pde.core/xstampp.product/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog

!ENTRY org.eclipse.equinox.p2.ui.importexport 4 0 2018-10-31 11:03:03.390
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.equinox.p2.ui.importexport [111]
  Unresolved requirement: Require-Bundle: org.eclipse.ui.forms; bundle-version="3.5.0"

	at org.eclipse.osgi.container.Module.start(Module.java:447)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1685)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1664)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1627)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1558)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:343)

!ENTRY org.eclipse.help.ui 4 0 2018-10-31 11:03:03.398
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.help.ui [126]
  Unresolved requirement: Require-Bundle: org.eclipse.ui.forms; bundle-version="[3.5.0,4.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:447)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1685)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1664)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1627)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1558)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:343)

!ENTRY xstampp.acast 4 0 2018-10-31 11:03:03.400
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: xstampp.acast [155]
  Unresolved requirement: Import-Package: xstampp.model
    -> Export-Package: xstampp.model; bundle-symbolic-name="xstampp"; bundle-version="3.1.1"; version="0.0.0"
       xstampp [166]
         Unresolved requirement: Require-Bundle: org.apache.commons.lang; bundle-version="2.6.0"
         Unresolved requirement: Require-Bundle: org.eclipse.help.ui
           -> Bundle-SymbolicName: org.eclipse.help.ui; bundle-version="4.1.200.v20180821-0700"; singleton:="true"
              org.eclipse.help.ui [126]
                Unresolved requirement: Require-Bundle: org.eclipse.ui.forms; bundle-version="[3.5.0,4.0.0)"
  Unresolved requirement: Require-Bundle: xstampp; bundle-version="1.0.2"
    -> Bundle-SymbolicName: xstampp; bundle-version="3.1.1"; singleton:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:447)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1685)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1664)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1627)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1558)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:343)

!ENTRY xstampp.astpa 4 0 2018-10-31 11:03:03.404
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: xstampp.astpa [156]
  Unresolved requirement: Require-Bundle: xstampp
    -> Bundle-SymbolicName: xstampp; bundle-version="3.1.1"; singleton:="true"
       xstampp [166]
         Unresolved requirement: Require-Bundle: org.apache.commons.lang; bundle-version="2.6.0"
         Unresolved requirement: Require-Bundle: org.eclipse.help.ui
           -> Bundle-SymbolicName: org.eclipse.help.ui; bundle-version="4.1.200.v20180821-0700"; singleton:="true"
              org.eclipse.help.ui [126]
                Unresolved requirement: Require-Bundle: org.eclipse.ui.forms; bundle-version="[3.5.0,4.0.0)"
  Unresolved requirement: Import-Package: org.apache.log4j
    -> Export-Package: org.apache.log4j; bundle-symbolic-name="xstampp"; bundle-version="3.1.1"; version="0.0.0"

	at org.eclipse.osgi.container.Module.start(Module.java:447)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1685)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1664)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1627)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1558)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:343)

!ENTRY xstampp.stpapriv 4 0 2018-10-31 11:03:03.406
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: xstampp.stpapriv [157]
  Unresolved requirement: Import-Package: org.apache.log4j
    -> Export-Package: org.apache.log4j; bundle-symbolic-name="xstampp"; bundle-version="3.1.1"; version="0.0.0"
       xstampp [166]
         Unresolved requirement: Require-Bundle: org.apache.commons.lang; bundle-version="2.6.0"
         Unresolved requirement: Require-Bundle: org.eclipse.help.ui
           -> Bundle-SymbolicName: org.eclipse.help.ui; bundle-version="4.1.200.v20180821-0700"; singleton:="true"
              org.eclipse.help.ui [126]
                Unresolved requirement: Require-Bundle: org.eclipse.ui.forms; bundle-version="[3.5.0,4.0.0)"
  Unresolved requirement: Require-Bundle: xstampp
    -> Bundle-SymbolicName: xstampp; bundle-version="3.1.1"; singleton:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:447)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1685)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1664)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1627)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1558)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:343)

!ENTRY xstampp.stpasec 4 0 2018-10-31 11:03:03.408
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: xstampp.stpasec [158]
  Unresolved requirement: Import-Package: org.apache.log4j
    -> Export-Package: org.apache.log4j; bundle-symbolic-name="xstampp"; bundle-version="3.1.1"; version="0.0.0"
       xstampp [166]
         Unresolved requirement: Require-Bundle: org.apache.commons.lang; bundle-version="2.6.0"
         Unresolved requirement: Require-Bundle: org.eclipse.help.ui
           -> Bundle-SymbolicName: org.eclipse.help.ui; bundle-version="4.1.200.v20180821-0700"; singleton:="true"
              org.eclipse.help.ui [126]
                Unresolved requirement: Require-Bundle: org.eclipse.ui.forms; bundle-version="[3.5.0,4.0.0)"
  Unresolved requirement: Require-Bundle: xstampp
    -> Bundle-SymbolicName: xstampp; bundle-version="3.1.1"; singleton:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:447)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1685)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1664)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1627)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1558)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:343)

!ENTRY xstampp.xstpa 4 0 2018-10-31 11:03:03.410
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: xstampp.xstpa [159]
  Unresolved requirement: Import-Package: org.eclipse.core.resources

	at org.eclipse.osgi.container.Module.start(Module.java:447)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1685)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1664)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1627)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1558)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:343)

!ENTRY xstampp.xstpapriv 4 0 2018-10-31 11:03:03.413
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: xstampp.xstpapriv [160]
  Unresolved requirement: Import-Package: org.eclipse.core.resources

	at org.eclipse.osgi.container.Module.start(Module.java:447)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1685)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1664)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1627)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1558)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:343)

!ENTRY xstampp.xstpasec 4 0 2018-10-31 11:03:03.414
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: xstampp.xstpasec [161]
  Unresolved requirement: Import-Package: org.eclipse.core.resources

	at org.eclipse.osgi.container.Module.start(Module.java:447)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1685)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1664)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1627)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1558)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:343)

!ENTRY xstampp 4 0 2018-10-31 11:03:03.416
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: xstampp [166]
  Unresolved requirement: Require-Bundle: org.apache.commons.lang; bundle-version="2.6.0"
  Unresolved requirement: Require-Bundle: org.eclipse.help.ui
    -> Bundle-SymbolicName: org.eclipse.help.ui; bundle-version="4.1.200.v20180821-0700"; singleton:="true"
       org.eclipse.help.ui [126]
         Unresolved requirement: Require-Bundle: org.eclipse.ui.forms; bundle-version="[3.5.0,4.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:447)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1685)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1664)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1627)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1558)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:343)

!ENTRY org.eclipse.equinox.app 0 0 2018-10-31 11:03:03.590
!MESSAGE Product xstampp.xstampp_product could not be found.

!ENTRY xstampp 2 0 2018-10-31 11:03:03.671
!MESSAGE Could not resolve module: xstampp [166]
  Unresolved requirement: Require-Bundle: org.eclipse.help.ui
    -> Bundle-SymbolicName: org.eclipse.help.ui; bundle-version="4.1.200.v20180821-0700"; singleton:="true"
       org.eclipse.help.ui [126]
         Unresolved requirement: Require-Bundle: org.eclipse.ui.forms; bundle-version="[3.5.0,4.0.0)"

!ENTRY xstampp.stpasec 2 0 2018-10-31 11:03:03.681
!MESSAGE Could not resolve module: xstampp.stpasec [158]
  Unresolved requirement: Import-Package: org.apache.log4j
    -> Export-Package: org.apache.log4j; bundle-symbolic-name="xstampp"; bundle-version="3.1.1"; version="0.0.0"
       xstampp [166]
         Unresolved requirement: Require-Bundle: org.eclipse.help.ui
           -> Bundle-SymbolicName: org.eclipse.help.ui; bundle-version="4.1.200.v20180821-0700"; singleton:="true"
              org.eclipse.help.ui [126]
                Unresolved requirement: Require-Bundle: org.eclipse.ui.forms; bundle-version="[3.5.0,4.0.0)"

!ENTRY xstampp.stpapriv 2 0 2018-10-31 11:03:03.683
!MESSAGE Could not resolve module: xstampp.stpapriv [157]
  Unresolved requirement: Import-Package: org.apache.log4j
    -> Export-Package: org.apache.log4j; bundle-symbolic-name="xstampp"; bundle-version="3.1.1"; version="0.0.0"
       xstampp [166]
         Unresolved requirement: Require-Bundle: org.eclipse.help.ui
           -> Bundle-SymbolicName: org.eclipse.help.ui; bundle-version="4.1.200.v20180821-0700"; singleton:="true"
              org.eclipse.help.ui [126]
                Unresolved requirement: Require-Bundle: org.eclipse.ui.forms; bundle-version="[3.5.0,4.0.0)"

!ENTRY xstampp.acast 2 0 2018-10-31 11:03:03.686
!MESSAGE Could not resolve module: xstampp.acast [155]
  Unresolved requirement: Import-Package: xstampp.model
    -> Export-Package: xstampp.model; bundle-symbolic-name="xstampp"; bundle-version="3.1.1"; version="0.0.0"
       xstampp [166]
         Unresolved requirement: Require-Bundle: org.eclipse.help.ui
           -> Bundle-SymbolicName: org.eclipse.help.ui; bundle-version="4.1.200.v20180821-0700"; singleton:="true"
              org.eclipse.help.ui [126]
                Unresolved requirement: Require-Bundle: org.eclipse.ui.forms; bundle-version="[3.5.0,4.0.0)"
  Unresolved requirement: Require-Bundle: xstampp; bundle-version="1.0.2"
    -> Bundle-SymbolicName: xstampp; bundle-version="3.1.1"; singleton:="true"

!ENTRY xstampp.xstpasec 2 0 2018-10-31 11:03:03.687
!MESSAGE Could not resolve module: xstampp.xstpasec [161]
  Unresolved requirement: Import-Package: org.eclipse.core.resources

!ENTRY xstampp.astpa 2 0 2018-10-31 11:03:03.689
!MESSAGE Could not resolve module: xstampp.astpa [156]
  Unresolved requirement: Import-Package: org.apache.log4j
    -> Export-Package: org.apache.log4j; bundle-symbolic-name="xstampp"; bundle-version="3.1.1"; version="0.0.0"
       xstampp [166]
         Unresolved requirement: Require-Bundle: org.eclipse.help.ui
           -> Bundle-SymbolicName: org.eclipse.help.ui; bundle-version="4.1.200.v20180821-0700"; singleton:="true"
              org.eclipse.help.ui [126]
                Unresolved requirement: Require-Bundle: org.eclipse.ui.forms; bundle-version="[3.5.0,4.0.0)"

!ENTRY org.eclipse.equinox.p2.ui.importexport 2 0 2018-10-31 11:03:03.691
!MESSAGE Could not resolve module: org.eclipse.equinox.p2.ui.importexport [111]
  Unresolved requirement: Require-Bundle: org.eclipse.ui.forms; bundle-version="3.5.0"

!ENTRY org.eclipse.help.ui 2 0 2018-10-31 11:03:03.693
!MESSAGE Could not resolve module: org.eclipse.help.ui [126]
  Unresolved requirement: Require-Bundle: org.eclipse.ui.forms; bundle-version="[3.5.0,4.0.0)"

!ENTRY xstampp.xstpapriv 2 0 2018-10-31 11:03:03.695
!MESSAGE Could not resolve module: xstampp.xstpapriv [160]
  Unresolved requirement: Import-Package: org.eclipse.core.resources

!ENTRY xstampp.xstpa 2 0 2018-10-31 11:03:03.697
!MESSAGE Could not resolve module: xstampp.xstpa [159]
  Unresolved requirement: Import-Package: org.eclipse.core.resources

!ENTRY org.eclipse.osgi 4 0 2018-10-31 11:03:03.711
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: No application id has been found.
	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:245)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:32)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)

**Comment by ljy5490** [comment]
https://stackoverflow.com/questions/32077485/unresolved-requirement-require-bundle-org-eclipse-core-databinding-beans-bund
The answer in the link solved my problem. I think I just clicked Add Required Plug-ins button and it worked.
